// Generated by scripts/generate-swift-theme.mjs from tokens.json. Do not edit.

import AppKit
import SwiftUI

public struct SettingsMetrics: Equatable, Sendable {
  public var cardRadius: CGFloat
  public var controlRadius: CGFloat
  public var rowInset: CGFloat
  public var contentWidth: CGFloat
  public var sectionSpacing: CGFloat

  public init(
    cardRadius: CGFloat = 14,
    controlRadius: CGFloat = 9,
    rowInset: CGFloat = 18,
    contentWidth: CGFloat = 720,
    sectionSpacing: CGFloat = 20
  ) {
    self.cardRadius = cardRadius
    self.controlRadius = controlRadius
    self.rowInset = rowInset
    self.contentWidth = contentWidth
    self.sectionSpacing = sectionSpacing
  }

  public static let standard = SettingsMetrics()
}

public struct SettingsTypography: Sendable {
  public var brandTitle: SettingsTextStyle
  public var brandSubtitle: SettingsTextStyle
  public var sidebarGroup: SettingsTextStyle
  public var sidebarItem: SettingsTextStyle
  public var sidebarItemSelected: SettingsTextStyle
  public var pageTitle: SettingsTextStyle
  public var pageSubtitle: SettingsTextStyle
  public var contentTitle: SettingsTextStyle
  public var body: SettingsTextStyle
  public var sectionHeader: SettingsTextStyle
  public var rowTitle: SettingsTextStyle
  public var rowCaption: SettingsTextStyle
  public var value: SettingsTextStyle
  public var sliderValue: SettingsTextStyle
  public var selectionLabel: SettingsTextStyle
  public var buttonLabel: SettingsTextStyle
  public var tag: SettingsTextStyle

  public init(
    brandTitle: SettingsTextStyle = SettingsTextStyle(
      size: 16,
      weight: .bold,
      design: .rounded
    ),
    brandSubtitle: SettingsTextStyle = SettingsTextStyle(
      size: 10.5,
      weight: .medium
    ),
    sidebarGroup: SettingsTextStyle = SettingsTextStyle(
      size: 9,
      weight: .semibold
    ),
    sidebarItem: SettingsTextStyle = SettingsTextStyle(size: 12.5),
    sidebarItemSelected: SettingsTextStyle = SettingsTextStyle(
      size: 12.5,
      weight: .semibold
    ),
    pageTitle: SettingsTextStyle = SettingsTextStyle(
      size: 25,
      weight: .semibold,
      design: .rounded
    ),
    pageSubtitle: SettingsTextStyle = SettingsTextStyle(size: 11.5),
    contentTitle: SettingsTextStyle = SettingsTextStyle(
      size: 21,
      weight: .semibold
    ),
    body: SettingsTextStyle = SettingsTextStyle(size: 12),
    sectionHeader: SettingsTextStyle = SettingsTextStyle(
      size: 10.5,
      weight: .semibold
    ),
    rowTitle: SettingsTextStyle = SettingsTextStyle(size: 13),
    rowCaption: SettingsTextStyle = SettingsTextStyle(size: 11),
    value: SettingsTextStyle = SettingsTextStyle(size: 12.5),
    sliderValue: SettingsTextStyle = SettingsTextStyle(
      size: 11.5,
      usesMonospacedDigits: true
    ),
    selectionLabel: SettingsTextStyle = SettingsTextStyle(
      size: 11.5,
      weight: .medium
    ),
    buttonLabel: SettingsTextStyle = SettingsTextStyle(
      size: 12.5,
      weight: .medium
    ),
    tag: SettingsTextStyle = SettingsTextStyle(
      size: 11,
      design: .monospaced
    )
  ) {
    self.brandTitle = brandTitle
    self.brandSubtitle = brandSubtitle
    self.sidebarGroup = sidebarGroup
    self.sidebarItem = sidebarItem
    self.sidebarItemSelected = sidebarItemSelected
    self.pageTitle = pageTitle
    self.pageSubtitle = pageSubtitle
    self.contentTitle = contentTitle
    self.body = body
    self.sectionHeader = sectionHeader
    self.rowTitle = rowTitle
    self.rowCaption = rowCaption
    self.value = value
    self.sliderValue = sliderValue
    self.selectionLabel = selectionLabel
    self.buttonLabel = buttonLabel
    self.tag = tag
  }

  public static let standard = SettingsTypography()
}

public struct SettingsSurfaces: Equatable, Sendable {
  public var canvas: Color
  public var sidebar: Color
  public var card: Color
  public var control: Color
  public var field: Color

  public init(
    canvas: Color = SettingsPalette.canvas,
    sidebar: Color = SettingsPalette.card,
    card: Color = SettingsPalette.control,
    control: Color = SettingsPalette.control,
    field: Color = SettingsPalette.field
  ) {
    self.canvas = canvas
    self.sidebar = sidebar
    self.card = card
    self.control = control
    self.field = field
  }

  public static let standard = SettingsSurfaces()
}

public struct SettingsViewConfiguration {
  public var applicationName: String
  public var settingsTitle: String
  public var applicationIcon: NSImage?
  public var sidebarFooter: String?
  public var defaultAccent: SettingsAccent
  public var strings: SettingsStrings
  public var metrics: SettingsMetrics
  public var typography: SettingsTypography
  public var surfaces: SettingsSurfaces
  public var sidebarWidth: CGFloat
  public var cornerRadius: CGFloat

  public init(
    applicationName: String,
    settingsTitle: String = "Settings",
    applicationIcon: NSImage? = nil,
    sidebarFooter: String? = nil,
    defaultAccent: SettingsAccent = .celadon,
    strings: SettingsStrings = SettingsStrings(),
    metrics: SettingsMetrics = .standard,
    typography: SettingsTypography = .standard,
    surfaces: SettingsSurfaces = .standard,
    sidebarWidth: CGFloat = 224,
    cornerRadius: CGFloat = 18
  ) {
    self.applicationName = applicationName
    self.settingsTitle = settingsTitle
    self.applicationIcon = applicationIcon
    self.sidebarFooter = sidebarFooter
    self.defaultAccent = defaultAccent
    self.strings = strings
    self.metrics = metrics
    self.typography = typography
    self.surfaces = surfaces
    self.sidebarWidth = sidebarWidth
    self.cornerRadius = cornerRadius
  }
}

enum SettingsAccentToken {
  static let base: UInt32 = 0x6D9EA5
  static let fillLightness = SettingsAppearanceValue<CGFloat>(
    light: 0,
    dark: 0.131
  )
  static let foregroundContrast = SettingsAppearanceValue<CGFloat>(
    light: -0.114,
    dark: 0.03
  )
}

extension SettingsAccent {
  public static let celadon = SettingsAccent.derived(
    base: SettingsAccentToken.base,
    fillLightness: SettingsAccentToken.fillLightness,
    foregroundContrast: SettingsAccentToken.foregroundContrast
  )
}

extension SettingsPalette {
  public static let canvas = SettingsPalette.dynamic(light: 0xFCFCFB, dark: 0x161617)
  public static let card = SettingsPalette.dynamic(light: 0xF2F2EF, dark: 0x232326)
  public static let control = SettingsPalette.dynamic(light: 0xFFFFFF, dark: 0x2E2E31)
  public static let field = SettingsPalette.dynamic(light: 0xE9E9E5, dark: 0x2A2A2D)
  public static let ink = SettingsPalette.dynamic(light: 0x1D1D1B, dark: 0xF1F1EF)
  public static let muted = SettingsPalette.dynamic(light: 0x6C6C66, dark: 0x9B9B96)
  public static let faint = SettingsPalette.dynamic(light: 0x91918A, dark: 0x8A8A84)
  public static let hairline = SettingsPalette.translucent(
    light: 0x000000,
    lightAlpha: 0.07,
    dark: 0xFFFFFF,
    darkAlpha: 0.09
  )
  public static let edge = SettingsPalette.translucent(
    light: 0x000000,
    lightAlpha: 0.05,
    dark: 0xFFFFFF,
    darkAlpha: 0.07
  )

  static let sliderKnobColor = SettingsPalette.dynamicNSColor(light: 0xFFFFFF, dark: 0xE2E2DE)
  static let sliderKnobBorderColor = SettingsPalette.dynamicNSColor(
    light: 0x000000,
    lightAlpha: 0.12,
    dark: 0x000000,
    darkAlpha: 0.42
  )
  static let closeHover = SettingsPalette.dynamic(light: 0xFF5F57, dark: 0xFF6961)
}

enum SettingsMotion {
  static let disclosure: TimeInterval = 0.18
  static let disclosureOffset: CGFloat = -5
  static let expand: TimeInterval = 0.18
  static let hover: TimeInterval = 0.12
  static let selection: TimeInterval = 0.16
  static let page: TimeInterval = 0.22
  static let defaultDuration: TimeInterval = 0.35
  static let reducedDisclosure: TimeInterval = 0.12
  static let reducedDisclosureOffset: CGFloat = 0
  static let reducedExpand: TimeInterval = 0.001
  static let reducedHover: TimeInterval = 0.001
  static let reducedSelection: TimeInterval = 0.001
  static let reducedPage: TimeInterval = 0.001
}
