// Generated by scripts/generate-swift-theme.mjs from tokens.json. Do not edit.

import SwiftUI

public struct FlowingMetrics: Equatable, Sendable {
  public var cardRadius: CGFloat
  public var controlRadius: CGFloat
  public var rowInset: CGFloat
  public var contentWidth: CGFloat
  public var sectionSpacing: CGFloat

  public init(
    cardRadius: CGFloat = 14,
    controlRadius: CGFloat = 9,
    rowInset: CGFloat = 18,
    contentWidth: CGFloat = 720,
    sectionSpacing: CGFloat = 20
  ) {
    self.cardRadius = cardRadius
    self.controlRadius = controlRadius
    self.rowInset = rowInset
    self.contentWidth = contentWidth
    self.sectionSpacing = sectionSpacing
  }

  public static let standard = FlowingMetrics()
}

public struct FlowingTypography: Sendable {
  public var brandTitle: FlowingTextStyle
  public var brandSubtitle: FlowingTextStyle
  public var sidebarGroup: FlowingTextStyle
  public var sidebarItem: FlowingTextStyle
  public var sidebarItemSelected: FlowingTextStyle
  public var pageTitle: FlowingTextStyle
  public var pageSubtitle: FlowingTextStyle
  public var contentTitle: FlowingTextStyle
  public var body: FlowingTextStyle
  public var sectionHeader: FlowingTextStyle
  public var rowTitle: FlowingTextStyle
  public var rowCaption: FlowingTextStyle
  public var value: FlowingTextStyle
  public var sliderValue: FlowingTextStyle
  public var selectionLabel: FlowingTextStyle
  public var buttonLabel: FlowingTextStyle
  public var tag: FlowingTextStyle

  public init(
    brandTitle: FlowingTextStyle = FlowingTextStyle(
      size: 16,
      weight: .bold,
      design: .rounded
    ),
    brandSubtitle: FlowingTextStyle = FlowingTextStyle(
      size: 10.5,
      weight: .medium
    ),
    sidebarGroup: FlowingTextStyle = FlowingTextStyle(
      size: 9,
      weight: .semibold
    ),
    sidebarItem: FlowingTextStyle = FlowingTextStyle(size: 12.5),
    sidebarItemSelected: FlowingTextStyle = FlowingTextStyle(
      size: 12.5,
      weight: .semibold
    ),
    pageTitle: FlowingTextStyle = FlowingTextStyle(
      size: 25,
      weight: .semibold,
      design: .rounded
    ),
    pageSubtitle: FlowingTextStyle = FlowingTextStyle(size: 11.5),
    contentTitle: FlowingTextStyle = FlowingTextStyle(
      size: 21,
      weight: .semibold
    ),
    body: FlowingTextStyle = FlowingTextStyle(size: 12),
    sectionHeader: FlowingTextStyle = FlowingTextStyle(
      size: 10.5,
      weight: .semibold
    ),
    rowTitle: FlowingTextStyle = FlowingTextStyle(size: 13),
    rowCaption: FlowingTextStyle = FlowingTextStyle(size: 11),
    value: FlowingTextStyle = FlowingTextStyle(size: 12.5),
    sliderValue: FlowingTextStyle = FlowingTextStyle(
      size: 11.5,
      usesMonospacedDigits: true
    ),
    selectionLabel: FlowingTextStyle = FlowingTextStyle(
      size: 11.5,
      weight: .medium
    ),
    buttonLabel: FlowingTextStyle = FlowingTextStyle(
      size: 12.5,
      weight: .medium
    ),
    tag: FlowingTextStyle = FlowingTextStyle(
      size: 11,
      design: .monospaced
    )
  ) {
    self.brandTitle = brandTitle
    self.brandSubtitle = brandSubtitle
    self.sidebarGroup = sidebarGroup
    self.sidebarItem = sidebarItem
    self.sidebarItemSelected = sidebarItemSelected
    self.pageTitle = pageTitle
    self.pageSubtitle = pageSubtitle
    self.contentTitle = contentTitle
    self.body = body
    self.sectionHeader = sectionHeader
    self.rowTitle = rowTitle
    self.rowCaption = rowCaption
    self.value = value
    self.sliderValue = sliderValue
    self.selectionLabel = selectionLabel
    self.buttonLabel = buttonLabel
    self.tag = tag
  }

  public static let standard = FlowingTypography()
}

public struct FlowingSurfaces: Equatable, Sendable {
  public var canvas: Color
  public var sidebar: Color
  public var card: Color
  public var control: Color
  public var field: Color

  public init(
    canvas: Color = FlowingPalette.canvas,
    sidebar: Color = FlowingPalette.card,
    card: Color = FlowingPalette.control,
    control: Color = FlowingPalette.control,
    field: Color = FlowingPalette.field
  ) {
    self.canvas = canvas
    self.sidebar = sidebar
    self.card = card
    self.control = control
    self.field = field
  }

  public static let standard = FlowingSurfaces()
}

enum FlowingAccentToken {
  static let base: UInt32 = 0x6D9EA5
  static let fillLightness = FlowingAppearanceValue<CGFloat>(
    light: 0,
    dark: 0.131
  )
  static let foregroundContrast = FlowingAppearanceValue<CGFloat>(
    light: -0.114,
    dark: 0.03
  )
}

extension FlowingAccent {
  public static let celadon = FlowingAccent.derived(
    base: FlowingAccentToken.base,
    fillLightness: FlowingAccentToken.fillLightness,
    foregroundContrast: FlowingAccentToken.foregroundContrast
  )
}

extension FlowingPalette {
  public static let canvas = FlowingPalette.dynamic(light: 0xFCFCFB, dark: 0x161617)
  public static let card = FlowingPalette.dynamic(light: 0xF2F2EF, dark: 0x232326)
  public static let control = FlowingPalette.dynamic(light: 0xFFFFFF, dark: 0x2E2E31)
  public static let field = FlowingPalette.dynamic(light: 0xFFFFFF, dark: 0x2A2A2D)
  public static let ink = FlowingPalette.dynamic(light: 0x1D1D1B, dark: 0xF1F1EF)
  public static let muted = FlowingPalette.dynamic(light: 0x6C6C66, dark: 0x9B9B96)
  public static let faint = FlowingPalette.dynamic(light: 0x91918A, dark: 0x8A8A84)
  public static let hairline = FlowingPalette.translucent(
    light: 0x000000,
    lightAlpha: 0.07,
    dark: 0xFFFFFF,
    darkAlpha: 0.09
  )
  public static let edge = FlowingPalette.translucent(
    light: 0x000000,
    lightAlpha: 0.05,
    dark: 0xFFFFFF,
    darkAlpha: 0.07
  )

  static let sliderKnobColor = FlowingPalette.dynamicNSColor(light: 0xFFFFFF, dark: 0xE2E2DE)
  static let sliderKnobBorderColor = FlowingPalette.dynamicNSColor(
    light: 0x000000,
    lightAlpha: 0.12,
    dark: 0x000000,
    darkAlpha: 0.42
  )
  public static let closeHover = FlowingPalette.dynamic(light: 0xFF5F57, dark: 0xFF6961)
}

public enum FlowingMotion {
  public static let disclosure: TimeInterval = 0.18
  public static let disclosureOffset: CGFloat = -5
  public static let expand: TimeInterval = 0.18
  public static let hover: TimeInterval = 0.12
  public static let selection: TimeInterval = 0.16
  public static let page: TimeInterval = 0.22
  public static let defaultDuration: TimeInterval = 0.35
  public static let reducedDisclosure: TimeInterval = 0.12
  public static let reducedDisclosureOffset: CGFloat = 0
  public static let reducedExpand: TimeInterval = 0.001
  public static let reducedHover: TimeInterval = 0.001
  public static let reducedSelection: TimeInterval = 0.001
  public static let reducedPage: TimeInterval = 0.001
}
