// Generated by scripts/generate-swift-theme.mjs from tokens.json. Do not edit.

enum FlowingNamedAccentBase {
  static let coral: UInt32 = 0xCE7B62
  static let poppy: UInt32 = 0xE96452
  static let crimson: UInt32 = 0xDF6B6F
  static let cherry: UInt32 = 0xE66176
  static let petal: UInt32 = 0xD67084
  static let rose: UInt32 = 0xD0748B
  static let berry: UInt32 = 0xDD62A7

  static let peach: UInt32 = 0xC3896B
  static let citrus: UInt32 = 0xC58458
  static let tangerine: UInt32 = 0xC58347
  static let nectar: UInt32 = 0xBB8C5B
  static let apricot: UInt32 = 0xB18D62
  static let amber: UInt32 = 0xB48C4A
  static let marigold: UInt32 = 0xB48F40

  static let butter: UInt32 = 0xA89565
  static let honey: UInt32 = 0xAC9326
  static let pollen: UInt32 = 0xA6974F
  static let sunbeam: UInt32 = 0xA49A54
  static let daffodil: UInt32 = 0xA29A41
  static let yuzu: UInt32 = 0xA09D3B
  static let lemon: UInt32 = 0x9CA12F

  static let leaf: UInt32 = 0x74A629
  static let sage: UInt32 = 0x76A454
  static let sprout: UInt32 = 0x60AB32
  static let meadow: UInt32 = 0x69A75F
  static let clover: UInt32 = 0x38AF55
  static let fern: UInt32 = 0x58A97B
  static let mint: UInt32 = 0x5EA88F

  static let dew: UInt32 = 0x66A49B
  static let seafoam: UInt32 = 0x4DA5A0
  static let lagoon: UInt32 = 0x3FA4A4
  static let tide: UInt32 = 0x59A3A7
  static let celadon: UInt32 = FlowingAccentToken.base
  static let ripple: UInt32 = 0x59A4B2
  static let mist: UInt32 = 0x72A3AF

  static let glacier: UInt32 = 0x56A4B7
  static let brook: UInt32 = 0x29A3C5
  static let sky: UInt32 = 0x62A4CA
  static let rain: UInt32 = 0x6CA0D3
  static let breeze: UInt32 = 0x6F92DE
  static let bluebell: UInt32 = 0x708DE5
  static let evening: UInt32 = 0x848CCF

  static let wisteria: UInt32 = 0x968AC7
  static let bloom: UInt32 = 0x9F82D5
  static let plum: UInt32 = 0xA483C7
  static let iris: UInt32 = 0xB86EE2
  static let lilac: UInt32 = 0xB681C6
  static let violet: UInt32 = 0xC868D4
  static let fuchsia: UInt32 = 0xCD6EB6

  static let all: [UInt32] = [
    coral, poppy, crimson, cherry, petal, rose, berry,
    peach, citrus, tangerine, nectar, apricot, amber, marigold,
    butter, honey, pollen, sunbeam, daffodil, yuzu, lemon,
    leaf, sage, sprout, meadow, clover, fern, mint,
    dew, seafoam, lagoon, tide, celadon, ripple, mist,
    glacier, brook, sky, rain, breeze, bluebell, evening,
    wisteria, bloom, plum, iris, lilac, violet, fuchsia,
  ]
}

extension FlowingAccent {
  public static let coral = named(base: FlowingNamedAccentBase.coral)
  public static let poppy = named(base: FlowingNamedAccentBase.poppy)
  public static let crimson = named(base: FlowingNamedAccentBase.crimson)
  public static let cherry = named(base: FlowingNamedAccentBase.cherry)
  public static let petal = named(base: FlowingNamedAccentBase.petal)
  public static let rose = named(base: FlowingNamedAccentBase.rose)
  public static let berry = named(base: FlowingNamedAccentBase.berry)

  public static let peach = named(base: FlowingNamedAccentBase.peach)
  public static let citrus = named(base: FlowingNamedAccentBase.citrus)
  public static let tangerine = named(base: FlowingNamedAccentBase.tangerine)
  public static let nectar = named(base: FlowingNamedAccentBase.nectar)
  public static let apricot = named(base: FlowingNamedAccentBase.apricot)
  public static let amber = named(base: FlowingNamedAccentBase.amber)
  public static let marigold = named(base: FlowingNamedAccentBase.marigold)

  public static let butter = named(base: FlowingNamedAccentBase.butter)
  public static let honey = named(base: FlowingNamedAccentBase.honey)
  public static let pollen = named(base: FlowingNamedAccentBase.pollen)
  public static let sunbeam = named(base: FlowingNamedAccentBase.sunbeam)
  public static let daffodil = named(base: FlowingNamedAccentBase.daffodil)
  public static let yuzu = named(base: FlowingNamedAccentBase.yuzu)
  public static let lemon = named(base: FlowingNamedAccentBase.lemon)

  public static let leaf = named(base: FlowingNamedAccentBase.leaf)
  public static let sage = named(base: FlowingNamedAccentBase.sage)
  public static let sprout = named(base: FlowingNamedAccentBase.sprout)
  public static let meadow = named(base: FlowingNamedAccentBase.meadow)
  public static let clover = named(base: FlowingNamedAccentBase.clover)
  public static let fern = named(base: FlowingNamedAccentBase.fern)
  public static let mint = named(base: FlowingNamedAccentBase.mint)

  public static let dew = named(base: FlowingNamedAccentBase.dew)
  public static let seafoam = named(base: FlowingNamedAccentBase.seafoam)
  public static let lagoon = named(base: FlowingNamedAccentBase.lagoon)
  public static let tide = named(base: FlowingNamedAccentBase.tide)
  public static let ripple = named(base: FlowingNamedAccentBase.ripple)
  public static let mist = named(base: FlowingNamedAccentBase.mist)

  public static let glacier = named(base: FlowingNamedAccentBase.glacier)
  public static let brook = named(base: FlowingNamedAccentBase.brook)
  public static let sky = named(base: FlowingNamedAccentBase.sky)
  public static let rain = named(base: FlowingNamedAccentBase.rain)
  public static let breeze = named(base: FlowingNamedAccentBase.breeze)
  public static let bluebell = named(base: FlowingNamedAccentBase.bluebell)
  public static let evening = named(base: FlowingNamedAccentBase.evening)

  public static let wisteria = named(base: FlowingNamedAccentBase.wisteria)
  public static let bloom = named(base: FlowingNamedAccentBase.bloom)
  public static let plum = named(base: FlowingNamedAccentBase.plum)
  public static let iris = named(base: FlowingNamedAccentBase.iris)
  public static let lilac = named(base: FlowingNamedAccentBase.lilac)
  public static let violet = named(base: FlowingNamedAccentBase.violet)
  public static let fuchsia = named(base: FlowingNamedAccentBase.fuchsia)

  private static func named(base: UInt32) -> FlowingAccent {
    FlowingAccent.derived(
      base: base,
      fillLightness: FlowingAccentToken.fillLightness,
      foregroundContrast: FlowingAccentToken.foregroundContrast
    )
  }
}
