// Generated by scripts/generate-swift-theme.mjs from tokens.json. Do not edit.

import AppKit
import FlowingDayControls
import SwiftUI

public struct PreferencesStrings: Equatable, Sendable {
  public var closePreferences: String
  public var controls: FlowingStrings

  public init(
    closePreferences: String = "Close Preferences",
    controls: FlowingStrings = FlowingStrings()
  ) {
    self.closePreferences = closePreferences
    self.controls = controls
  }
}

public enum PreferencesContentWidthPolicy: Equatable, Sendable {
  case fluid
  case centered(maximumWidth: CGFloat? = nil)

  func resolvedMaximumWidth(defaultWidth: CGFloat) -> CGFloat? {
    switch self {
    case .fluid:
      return nil
    case .centered(let maximumWidth):
      let fallback = defaultWidth.isFinite && defaultWidth > 0 ? defaultWidth : 1
      guard let maximumWidth else { return fallback }
      return maximumWidth.isFinite && maximumWidth > 0 ? maximumWidth : fallback
    }
  }
}

public struct PreferencesViewConfiguration {
  public var applicationName: String
  public var preferencesTitle: String
  public var applicationIcon: NSImage?
  public var sidebarFooter: String?
  public var defaultAccent: FlowingAccent
  public var strings: PreferencesStrings
  public var metrics: FlowingMetrics
  public var typography: FlowingTypography
  public var surfaces: FlowingSurfaces
  public var contentWidthPolicy: PreferencesContentWidthPolicy
  public var sidebarWidth: CGFloat
  public var cornerRadius: CGFloat

  public init(
    applicationName: String,
    preferencesTitle: String = "Preferences",
    applicationIcon: NSImage? = nil,
    sidebarFooter: String? = nil,
    defaultAccent: FlowingAccent = .celadon,
    strings: PreferencesStrings = PreferencesStrings(),
    metrics: FlowingMetrics = .standard,
    typography: FlowingTypography = .standard,
    surfaces: FlowingSurfaces = .standard,
    contentWidthPolicy: PreferencesContentWidthPolicy = .centered(),
    sidebarWidth: CGFloat = 224,
    cornerRadius: CGFloat = 18
  ) {
    self.applicationName = applicationName
    self.preferencesTitle = preferencesTitle
    self.applicationIcon = applicationIcon
    self.sidebarFooter = sidebarFooter
    self.defaultAccent = defaultAccent
    self.strings = strings
    self.metrics = metrics
    self.typography = typography
    self.surfaces = surfaces
    self.contentWidthPolicy = contentWidthPolicy
    self.sidebarWidth = sidebarWidth
    self.cornerRadius = cornerRadius
  }
}
