// Generated by scripts/generate-swift-theme.mjs from tokens.json. Do not edit.

enum PreferencesNamedAccentBase {
  static let coral: UInt32 = 0xCE7B62
  static let poppy: UInt32 = 0xE96452
  static let crimson: UInt32 = 0xDF6B6F
  static let cherry: UInt32 = 0xE66176
  static let petal: UInt32 = 0xD67084
  static let rose: UInt32 = 0xD0748B
  static let berry: UInt32 = 0xDD62A7

  static let peach: UInt32 = 0xC3896B
  static let citrus: UInt32 = 0xC58458
  static let tangerine: UInt32 = 0xC58347
  static let nectar: UInt32 = 0xBB8C5B
  static let apricot: UInt32 = 0xB18D62
  static let amber: UInt32 = 0xB48C4A
  static let marigold: UInt32 = 0xB48F40

  static let butter: UInt32 = 0xA89565
  static let honey: UInt32 = 0xAC9326
  static let pollen: UInt32 = 0xA6974F
  static let sunbeam: UInt32 = 0xA49A54
  static let daffodil: UInt32 = 0xA29A41
  static let yuzu: UInt32 = 0xA09D3B
  static let lemon: UInt32 = 0x9CA12F

  static let leaf: UInt32 = 0x74A629
  static let sage: UInt32 = 0x76A454
  static let sprout: UInt32 = 0x60AB32
  static let meadow: UInt32 = 0x69A75F
  static let clover: UInt32 = 0x38AF55
  static let fern: UInt32 = 0x58A97B
  static let mint: UInt32 = 0x5EA88F

  static let dew: UInt32 = 0x66A49B
  static let seafoam: UInt32 = 0x4DA5A0
  static let lagoon: UInt32 = 0x3FA4A4
  static let tide: UInt32 = 0x59A3A7
  static let celadon: UInt32 = PreferencesAccentToken.base
  static let ripple: UInt32 = 0x59A4B2
  static let mist: UInt32 = 0x72A3AF

  static let glacier: UInt32 = 0x56A4B7
  static let brook: UInt32 = 0x29A3C5
  static let sky: UInt32 = 0x62A4CA
  static let rain: UInt32 = 0x6CA0D3
  static let breeze: UInt32 = 0x6F92DE
  static let bluebell: UInt32 = 0x708DE5
  static let evening: UInt32 = 0x848CCF

  static let wisteria: UInt32 = 0x968AC7
  static let bloom: UInt32 = 0x9F82D5
  static let plum: UInt32 = 0xA483C7
  static let iris: UInt32 = 0xB86EE2
  static let lilac: UInt32 = 0xB681C6
  static let violet: UInt32 = 0xC868D4
  static let fuchsia: UInt32 = 0xCD6EB6

  static let all: [UInt32] = [
    coral, poppy, crimson, cherry, petal, rose, berry,
    peach, citrus, tangerine, nectar, apricot, amber, marigold,
    butter, honey, pollen, sunbeam, daffodil, yuzu, lemon,
    leaf, sage, sprout, meadow, clover, fern, mint,
    dew, seafoam, lagoon, tide, celadon, ripple, mist,
    glacier, brook, sky, rain, breeze, bluebell, evening,
    wisteria, bloom, plum, iris, lilac, violet, fuchsia,
  ]
}

extension PreferencesAccent {
  public static let coral = named(base: PreferencesNamedAccentBase.coral)
  public static let poppy = named(base: PreferencesNamedAccentBase.poppy)
  public static let crimson = named(base: PreferencesNamedAccentBase.crimson)
  public static let cherry = named(base: PreferencesNamedAccentBase.cherry)
  public static let petal = named(base: PreferencesNamedAccentBase.petal)
  public static let rose = named(base: PreferencesNamedAccentBase.rose)
  public static let berry = named(base: PreferencesNamedAccentBase.berry)

  public static let peach = named(base: PreferencesNamedAccentBase.peach)
  public static let citrus = named(base: PreferencesNamedAccentBase.citrus)
  public static let tangerine = named(base: PreferencesNamedAccentBase.tangerine)
  public static let nectar = named(base: PreferencesNamedAccentBase.nectar)
  public static let apricot = named(base: PreferencesNamedAccentBase.apricot)
  public static let amber = named(base: PreferencesNamedAccentBase.amber)
  public static let marigold = named(base: PreferencesNamedAccentBase.marigold)

  public static let butter = named(base: PreferencesNamedAccentBase.butter)
  public static let honey = named(base: PreferencesNamedAccentBase.honey)
  public static let pollen = named(base: PreferencesNamedAccentBase.pollen)
  public static let sunbeam = named(base: PreferencesNamedAccentBase.sunbeam)
  public static let daffodil = named(base: PreferencesNamedAccentBase.daffodil)
  public static let yuzu = named(base: PreferencesNamedAccentBase.yuzu)
  public static let lemon = named(base: PreferencesNamedAccentBase.lemon)

  public static let leaf = named(base: PreferencesNamedAccentBase.leaf)
  public static let sage = named(base: PreferencesNamedAccentBase.sage)
  public static let sprout = named(base: PreferencesNamedAccentBase.sprout)
  public static let meadow = named(base: PreferencesNamedAccentBase.meadow)
  public static let clover = named(base: PreferencesNamedAccentBase.clover)
  public static let fern = named(base: PreferencesNamedAccentBase.fern)
  public static let mint = named(base: PreferencesNamedAccentBase.mint)

  public static let dew = named(base: PreferencesNamedAccentBase.dew)
  public static let seafoam = named(base: PreferencesNamedAccentBase.seafoam)
  public static let lagoon = named(base: PreferencesNamedAccentBase.lagoon)
  public static let tide = named(base: PreferencesNamedAccentBase.tide)
  public static let ripple = named(base: PreferencesNamedAccentBase.ripple)
  public static let mist = named(base: PreferencesNamedAccentBase.mist)

  public static let glacier = named(base: PreferencesNamedAccentBase.glacier)
  public static let brook = named(base: PreferencesNamedAccentBase.brook)
  public static let sky = named(base: PreferencesNamedAccentBase.sky)
  public static let rain = named(base: PreferencesNamedAccentBase.rain)
  public static let breeze = named(base: PreferencesNamedAccentBase.breeze)
  public static let bluebell = named(base: PreferencesNamedAccentBase.bluebell)
  public static let evening = named(base: PreferencesNamedAccentBase.evening)

  public static let wisteria = named(base: PreferencesNamedAccentBase.wisteria)
  public static let bloom = named(base: PreferencesNamedAccentBase.bloom)
  public static let plum = named(base: PreferencesNamedAccentBase.plum)
  public static let iris = named(base: PreferencesNamedAccentBase.iris)
  public static let lilac = named(base: PreferencesNamedAccentBase.lilac)
  public static let violet = named(base: PreferencesNamedAccentBase.violet)
  public static let fuchsia = named(base: PreferencesNamedAccentBase.fuchsia)

  private static func named(base: UInt32) -> PreferencesAccent {
    PreferencesAccent.derived(
      base: base,
      fillLightness: PreferencesAccentToken.fillLightness,
      foregroundContrast: PreferencesAccentToken.foregroundContrast
    )
  }
}
