// Generated by scripts/generate-swift-theme.mjs from tokens.json. Do not edit.

import AppKit
import SwiftUI

public struct PreferencesMetrics: Equatable, Sendable {
  public var cardRadius: CGFloat
  public var controlRadius: CGFloat
  public var rowInset: CGFloat
  public var contentWidth: CGFloat
  public var sectionSpacing: CGFloat

  public init(
    cardRadius: CGFloat = 14,
    controlRadius: CGFloat = 9,
    rowInset: CGFloat = 18,
    contentWidth: CGFloat = 720,
    sectionSpacing: CGFloat = 20
  ) {
    self.cardRadius = cardRadius
    self.controlRadius = controlRadius
    self.rowInset = rowInset
    self.contentWidth = contentWidth
    self.sectionSpacing = sectionSpacing
  }

  public static let standard = PreferencesMetrics()
}

public struct PreferencesTypography: Sendable {
  public var brandTitle: PreferencesTextStyle
  public var brandSubtitle: PreferencesTextStyle
  public var sidebarGroup: PreferencesTextStyle
  public var sidebarItem: PreferencesTextStyle
  public var sidebarItemSelected: PreferencesTextStyle
  public var pageTitle: PreferencesTextStyle
  public var pageSubtitle: PreferencesTextStyle
  public var contentTitle: PreferencesTextStyle
  public var body: PreferencesTextStyle
  public var sectionHeader: PreferencesTextStyle
  public var rowTitle: PreferencesTextStyle
  public var rowCaption: PreferencesTextStyle
  public var value: PreferencesTextStyle
  public var sliderValue: PreferencesTextStyle
  public var selectionLabel: PreferencesTextStyle
  public var buttonLabel: PreferencesTextStyle
  public var tag: PreferencesTextStyle

  public init(
    brandTitle: PreferencesTextStyle = PreferencesTextStyle(
      size: 16,
      weight: .bold,
      design: .rounded
    ),
    brandSubtitle: PreferencesTextStyle = PreferencesTextStyle(
      size: 10.5,
      weight: .medium
    ),
    sidebarGroup: PreferencesTextStyle = PreferencesTextStyle(
      size: 9,
      weight: .semibold
    ),
    sidebarItem: PreferencesTextStyle = PreferencesTextStyle(size: 12.5),
    sidebarItemSelected: PreferencesTextStyle = PreferencesTextStyle(
      size: 12.5,
      weight: .semibold
    ),
    pageTitle: PreferencesTextStyle = PreferencesTextStyle(
      size: 25,
      weight: .semibold,
      design: .rounded
    ),
    pageSubtitle: PreferencesTextStyle = PreferencesTextStyle(size: 11.5),
    contentTitle: PreferencesTextStyle = PreferencesTextStyle(
      size: 21,
      weight: .semibold
    ),
    body: PreferencesTextStyle = PreferencesTextStyle(size: 12),
    sectionHeader: PreferencesTextStyle = PreferencesTextStyle(
      size: 10.5,
      weight: .semibold
    ),
    rowTitle: PreferencesTextStyle = PreferencesTextStyle(size: 13),
    rowCaption: PreferencesTextStyle = PreferencesTextStyle(size: 11),
    value: PreferencesTextStyle = PreferencesTextStyle(size: 12.5),
    sliderValue: PreferencesTextStyle = PreferencesTextStyle(
      size: 11.5,
      usesMonospacedDigits: true
    ),
    selectionLabel: PreferencesTextStyle = PreferencesTextStyle(
      size: 11.5,
      weight: .medium
    ),
    buttonLabel: PreferencesTextStyle = PreferencesTextStyle(
      size: 12.5,
      weight: .medium
    ),
    tag: PreferencesTextStyle = PreferencesTextStyle(
      size: 11,
      design: .monospaced
    )
  ) {
    self.brandTitle = brandTitle
    self.brandSubtitle = brandSubtitle
    self.sidebarGroup = sidebarGroup
    self.sidebarItem = sidebarItem
    self.sidebarItemSelected = sidebarItemSelected
    self.pageTitle = pageTitle
    self.pageSubtitle = pageSubtitle
    self.contentTitle = contentTitle
    self.body = body
    self.sectionHeader = sectionHeader
    self.rowTitle = rowTitle
    self.rowCaption = rowCaption
    self.value = value
    self.sliderValue = sliderValue
    self.selectionLabel = selectionLabel
    self.buttonLabel = buttonLabel
    self.tag = tag
  }

  public static let standard = PreferencesTypography()
}

public struct PreferencesSurfaces: Equatable, Sendable {
  public var canvas: Color
  public var sidebar: Color
  public var card: Color
  public var control: Color
  public var field: Color

  public init(
    canvas: Color = PreferencesPalette.canvas,
    sidebar: Color = PreferencesPalette.card,
    card: Color = PreferencesPalette.control,
    control: Color = PreferencesPalette.control,
    field: Color = PreferencesPalette.field
  ) {
    self.canvas = canvas
    self.sidebar = sidebar
    self.card = card
    self.control = control
    self.field = field
  }

  public static let standard = PreferencesSurfaces()
}

public enum PreferencesContentWidthPolicy: Equatable, Sendable {
  case fluid
  case centered(maximumWidth: CGFloat? = nil)

  func resolvedMaximumWidth(defaultWidth: CGFloat) -> CGFloat? {
    switch self {
    case .fluid:
      return nil
    case .centered(let maximumWidth):
      let fallback = defaultWidth.isFinite && defaultWidth > 0 ? defaultWidth : 1
      guard let maximumWidth else { return fallback }
      return maximumWidth.isFinite && maximumWidth > 0 ? maximumWidth : fallback
    }
  }
}

public struct PreferencesViewConfiguration {
  public var applicationName: String
  public var preferencesTitle: String
  public var applicationIcon: NSImage?
  public var sidebarFooter: String?
  public var defaultAccent: PreferencesAccent
  public var strings: PreferencesStrings
  public var metrics: PreferencesMetrics
  public var typography: PreferencesTypography
  public var surfaces: PreferencesSurfaces
  public var contentWidthPolicy: PreferencesContentWidthPolicy
  public var sidebarWidth: CGFloat
  public var cornerRadius: CGFloat

  public init(
    applicationName: String,
    preferencesTitle: String = "Preferences",
    applicationIcon: NSImage? = nil,
    sidebarFooter: String? = nil,
    defaultAccent: PreferencesAccent = .celadon,
    strings: PreferencesStrings = PreferencesStrings(),
    metrics: PreferencesMetrics = .standard,
    typography: PreferencesTypography = .standard,
    surfaces: PreferencesSurfaces = .standard,
    contentWidthPolicy: PreferencesContentWidthPolicy = .centered(),
    sidebarWidth: CGFloat = 224,
    cornerRadius: CGFloat = 18
  ) {
    self.applicationName = applicationName
    self.preferencesTitle = preferencesTitle
    self.applicationIcon = applicationIcon
    self.sidebarFooter = sidebarFooter
    self.defaultAccent = defaultAccent
    self.strings = strings
    self.metrics = metrics
    self.typography = typography
    self.surfaces = surfaces
    self.contentWidthPolicy = contentWidthPolicy
    self.sidebarWidth = sidebarWidth
    self.cornerRadius = cornerRadius
  }
}

enum PreferencesAccentToken {
  static let base: UInt32 = 0x6D9EA5
  static let fillLightness = PreferencesAppearanceValue<CGFloat>(
    light: 0,
    dark: 0.131
  )
  static let foregroundContrast = PreferencesAppearanceValue<CGFloat>(
    light: -0.114,
    dark: 0.03
  )
}

extension PreferencesAccent {
  public static let celadon = PreferencesAccent.derived(
    base: PreferencesAccentToken.base,
    fillLightness: PreferencesAccentToken.fillLightness,
    foregroundContrast: PreferencesAccentToken.foregroundContrast
  )
}

extension PreferencesPalette {
  public static let canvas = PreferencesPalette.dynamic(light: 0xFCFCFB, dark: 0x161617)
  public static let card = PreferencesPalette.dynamic(light: 0xF2F2EF, dark: 0x232326)
  public static let control = PreferencesPalette.dynamic(light: 0xFFFFFF, dark: 0x2E2E31)
  public static let field = PreferencesPalette.dynamic(light: 0xFFFFFF, dark: 0x2A2A2D)
  public static let ink = PreferencesPalette.dynamic(light: 0x1D1D1B, dark: 0xF1F1EF)
  public static let muted = PreferencesPalette.dynamic(light: 0x6C6C66, dark: 0x9B9B96)
  public static let faint = PreferencesPalette.dynamic(light: 0x91918A, dark: 0x8A8A84)
  public static let hairline = PreferencesPalette.translucent(
    light: 0x000000,
    lightAlpha: 0.07,
    dark: 0xFFFFFF,
    darkAlpha: 0.09
  )
  public static let edge = PreferencesPalette.translucent(
    light: 0x000000,
    lightAlpha: 0.05,
    dark: 0xFFFFFF,
    darkAlpha: 0.07
  )

  static let sliderKnobColor = PreferencesPalette.dynamicNSColor(light: 0xFFFFFF, dark: 0xE2E2DE)
  static let sliderKnobBorderColor = PreferencesPalette.dynamicNSColor(
    light: 0x000000,
    lightAlpha: 0.12,
    dark: 0x000000,
    darkAlpha: 0.42
  )
  static let closeHover = PreferencesPalette.dynamic(light: 0xFF5F57, dark: 0xFF6961)
}

enum PreferencesMotion {
  static let disclosure: TimeInterval = 0.18
  static let disclosureOffset: CGFloat = -5
  static let expand: TimeInterval = 0.18
  static let hover: TimeInterval = 0.12
  static let selection: TimeInterval = 0.16
  static let page: TimeInterval = 0.22
  static let defaultDuration: TimeInterval = 0.35
  static let reducedDisclosure: TimeInterval = 0.12
  static let reducedDisclosureOffset: CGFloat = 0
  static let reducedExpand: TimeInterval = 0.001
  static let reducedHover: TimeInterval = 0.001
  static let reducedSelection: TimeInterval = 0.001
  static let reducedPage: TimeInterval = 0.001
}
